Adjust osx makefile + silent for extensions

diff --git a/extensions/fancy-backtrace/Makefile.osx b/extensions/fancy-backtrace/Makefile.osx
--- a/extensions/fancy-backtrace/Makefile.osx
+++ b/extensions/fancy-backtrace/Makefile.osx
@@ -1,10 +1,10 @@
 .PHONY: build check clean
 
-GETTEXT:=$(shell brew info gettext | grep 'Cellar' | head -1 | cut -d ' ' -f 1)
-BINUTILS:=$(shell brew info binutils | grep 'Cellar' | head -1 | cut -d ' ' -f 1)
+GETTEXT := $(shell brew info gettext | grep 'Cellar' | head -1 | cut -d ' ' -f 1)
+BINUTILS := $(shell brew info binutils | grep 'Cellar' | head -1 | cut -d ' ' -f 1)
 
-DEBUG_FLAGS:=-fno-pie -g
-OSX_FLAGS:=-I$(GETTEXT)/include -I$(BINUTILS)/include -L$(GETTEXT)/lib -L$(BINUTILS)/lib/ -L$(BINUTILS)/lib/x86_64/
+DEBUG_FLAGS := -fno-pie -g
+OSX_FLAGS := -I$(GETTEXT)/include -I$(BINUTILS)/include -L$(GETTEXT)/lib -L$(BINUTILS)/lib/ -L$(BINUTILS)/lib/x86_64/
 
 build : check fancy_backtrace.dylib
 	cp -rf fancy_backtrace.dylib* ${BINDIR}/
@@ -17,11 +17,11 @@ clean :
 
 check :
 ifeq ($(GETTEXT),)
-	echo "gettext not found! install it via 'brew install gettext'"
-	exit 1
+	@echo "[WARNING] gettext not found! install it via 'brew install gettext'"
+	@exit 1
 endif
 
 ifeq ($(BINUTILS),)
-	echo "binutils not found! install it via 'brew install binutils'"
-	exit 1
+	@echo "[WARNING] binutils not found! install it via 'brew install binutils'"
+	@exit 1
 endif
