Add check for binutils / zlib on linux

diff --git a/extensions/backtrace/Makefile.osx b/extensions/backtrace/Makefile.osx
--- a/extensions/backtrace/Makefile.osx
+++ b/extensions/backtrace/Makefile.osx
@@ -1,26 +1,28 @@
-.PHONY: build clean
+.PHONY: build check clean
 
 GETTEXT:=$(shell brew info gettext | grep 'Cellar' | head -1 | cut -d ' ' -f 1)
-ifeq ($(GETTEXT),)
-  echo "gettext not found! install it via 'brew install gettext'"
-  exit 1
-endif
-
 BINUTILS:=$(shell brew info binutils | grep 'Cellar' | head -1 | cut -d ' ' -f 1)
-ifeq ($(BINUTILS),)
-  echo "binutils not found! install it via 'brew install binutils'"
-  exit 1
-endif
 
 DEBUG_FLAGS:=-fno-pie -g
 OSX_FLAGS:=-I$(GETTEXT)/include -I$(BINUTILS)/include -L$(GETTEXT)/lib -L$(BINUTILS)/lib/ -L$(BINUTILS)/lib/x86_64/
 
-build : backtrace.dylib
-	cp $^ ${BINDIR}/
+build : check backtrace.dylib
+	cp -rf backtrace.dylib* ${BINDIR}/
 
 backtrace.dylib : backtrace.c
 	gcc ${DEBUG_FLAGS} ${OSX_FLAGS} -DBUILDING_BACKTRACE_LIB -fPIC -O2 -shared -Wall -o $@ $^ -lbfd -lintl -liberty -lz
 
 clean :
 	@rm -rf backtrace.dylib backtrace.dSYM
+
+check :
+ifeq ($(GETTEXT),)
+	echo "gettext not found! install it via 'brew install gettext'"
+	exit 1
+endif
+
+ifeq ($(BINUTILS),)
+	echo "binutils not found! install it via 'brew install binutils'"
+	exit 1
+endif
 
